# Generated by Django 3.1.6 on 2023-05-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sign', models.CharField(max_length=20)),
                ('travail', models.TextField(default="pas d'horoscopes pour le moment")),
                ('argent', models.TextField(default="pas d'horoscopes pour le moment")),
                ('sante', models.TextField(default="pas d'horoscopes pour le moment")),
                ('amour', models.TextField(default="pas d'horoscopes pour le moment")),
                ('nombre', models.TextField(default="pas d'horoscopes pour le moment")),
                ('famille', models.TextField(default="pas d'horoscopes pour le moment")),
            ],
            options={
                'unique_together': {('date', 'sign')},
            },
        ),
    ]
