# Generated by Django 3.1.6 on 2023-05-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signa', '0002_remove_horoscope_famille'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='general',
            field=models.TextField(default="pas d'horoscopes pour le moment"),
        ),
    ]
