"""
Django settings for Asrto project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




SECRET_KEY = '3o+*f@$^jn55sz86q=ns$yv8jkh+%8*(-*v*tan8dv$asp^gt^'


DEBUG = False

ALLOWED_HOSTS = ['*']

#STATIC_ROOT ="static"

STATICFILES_DIRS = [
     BASE_DIR/"Asrto/static",
     BASE_DIR/"accounts/static",
]

PUBLIC_TEST ='pk_test_51MxcSDBmNIwWn8QE7627q43kcoHFW4sZyj39nR2I2jllOB1EEIPdtzG0OtXSzQzpmVhyZMmVX6u4r08MkwubDaM100Ak8fKN3F'
PRIVATE_TEST='sk_test_51MxcSDBmNIwWn8QE438kN6jL5efQEh5I1MYgulRByImQN356nSKuIj2jxOwCDLnYeXkPWwLq7NGUWrklUOqqvAiF00aJE7vCnz'


PUBLIC = 'pk_live_51MxcSDBmNIwWn8QEvUwaOzjqPtuiY7aTHbiR97QU3TL83vr2HVBkpFHXMUAMwvxkUYnlptjgYDGmCEFjc2sEc2jL00G2CsL11B'
PRIVATE = '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'


STRIPE_WEBHOOK_SECRET = 'whsec_b44jjJoJmsZwveSo56W1smY2XD68NPN8'



LOCAL_HOST = 'http://127.0.0.1:8000'



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Signa',
    'accounts',
    'paiement',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Asrto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"Asrto/templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Asrto.wsgi.application'


'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'test',
        'USER': 'postgres',
        'PASSWORD': 'Piegeamorue@33',
        'HOST': 'localhost',
        'PORT': '',
    }
}
'''

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'data33',
        'USER': 'astro',
        'PASSWORD': 'astro',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}





AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True




STATIC_URL = '/static/'

AUTH_USER_MODEL = "accounts.Client"

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


